steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'snapshots', 'create', 'gce-image-vm1', '--source-disk', 'vm1-s4rv', '--source-disk-zone','us-central1-a', '--project', '$PROJECT_ID']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'cloudBuild/nodejs/app.yaml', '--project', '$PROJECT_ID']
  secretEnv: ['BD_Pass', 'BD_ConnString']
  env:
  - 'Storage_Conn=random-conn-string'
  - 'Kv_Conn=another-random-conn-string'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx-arroyo-app', 'cloudBuild/docker/']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/nginx-arroyo-app']

images: ['gcr.io/$PROJECT_ID/gce-image-vm1']

availableSecrets:
  secretManager:
  - versionName: projects/191099355239/secrets/dbconn/versions/1
    env: 'BD_ConnString'
  - versionName: projects/191099355239/secrets/dbpass/versions/1
    env: 'BD_Pass'
